title: "RemoteHub 공지사항"
baseurl: "/remotehub/notice"
permalink: /:year/:month/:day/:title/
markdown: kramdown
lang: ko

source: .
destination: ./_site

collections_dir: .
posts_dir: _posts

# 다른 폴더 포스트 스캔 방지
exclude:
  - "../../tinyssh"
  - "../../../tinyssh"
